config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'admin_controller/refresh'

  root 'session#unauth'
  resources :users

  get 'session/unauth', to: 'session#unauth', as: :login
  post 'session/login', as: :signin
  delete 'session/logout', as: :logout

  get '/index', to: 'importer#index', as: 'articles'
  get '/interests', to: 'importer#my_interests', as: 'interests'
  get '/admin/scrape', to: 'admin#scrape', as: 'scrape'
  get '/admin/tag', to: 'admin#tag', as: 'tag'
  get '/admin/mail', to: 'admin#mail', as: 'mail'

  get '/admin', to: 'admin#index', as: 'index'

end

app/controllers/session_controller.rb
# This controller authenticates a User login
class SessionController < ApplicationController
  # Before actions to check paramters
  before_action :check_params, only: [:login]
  before_action :authenticate_user, only: [:logout]

  # Find a user with the email and email password
  # log in that user if they exist
  def login
    # Find a user with params
    user = User.authenticate(@credentials[:password], @credentials[:username])
    if user
      # Save them in the session
      log_in user
      # Redirect to posts page
      redirect_to articles_path
    else
      redirect_to :back, status: 403
    end
  end

  # Log out the user in the session and redirect to the /session/unauth
  def logout
    log_out
    redirect_to login_path
  end

  private

  def check_params
    params.require(:credentials).permit(:password, :username)
    @credentials = params[:credentials]
  end
end

app/helpers/session_helper.rb
# Session Helper
module SessionHelper
  # Log a user in after authenticating, store in session
  def log_in(user)
    session[:user_id] = user.id
  end

  # Return the currently logged in user for this session
  def current_user
    if !@current_user
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  # Log out for a user
  def log_out
    session[:user_id] = nil
  end
end

app/views/session/unauth.html.erb
<div class="row">
  	<div class="col-md-8">
		<div class="jumbotron">
		  <h1>The Digest</h1>
		  <p><%= link_to "Sign Up Today!", new_user_path, class:'btn btn-primary btn-lg' %></p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
  			<div class="panel-heading">Log In!</div>
  			<div class="panel-body">
				<%= form_for(:credentials, url: signin_path) do |f| %>
				  	<div class="form-group">
						<%= f.label :username%>
						<%= f.text_field :username, class: 'form-control'%>
					</div>
						<div class="form-group">
						<%= f.label :password%>
						<%= f.password_field :password, class: 'form-control'%>
					</div>
					<%= submit_tag %>
				<% end %>
			</div>
		</div>
	</div>
</div>